In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('dataset - dataset.csv')

In [3]:
data.head()

Unnamed: 0                                            comment  \
0           0  kon kon sourav joshi ka fan he channel ko subs...   
1           1       this playlist is very good best way to learn   
2           2                              completed the lecture   
3           3  you ve quickly become one of my favorite youtu...   
4           4  my name ghulk hello jonny bhai i m yourbig fan...   

      sentiment Unnamed: 3  
0  appreciation        NaN  
1  appreciation        NaN  
2        normal        NaN  
3  appreciation        NaN  
4      question        NaN

In [4]:
sample = data[['comment','sentiment']]

In [5]:
d1 = sample[sample['sentiment']=='trolling']
d2 = sample[sample['sentiment']=='appreciation']
d3 = sample[sample['sentiment']=='normal']
d4 = sample[sample['sentiment']=='suggestion']
d5 = sample[sample['sentiment']=='question']

sample2 = pd.concat([d1, d2, d3, d4, d5,d1, d2, d3, d4, d5])

In [6]:
sample2.reset_index(drop=True,inplace=True)

In [7]:
sample2['sentiment'].value_counts()

normal          5646
question        4762
appreciation    4268
suggestion      4056
trolling        1972
Name: sentiment, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [9]:
Y = encoder.fit_transform(sample2['sentiment'])
encoder.classes_

array(['appreciation', 'normal', 'question', 'suggestion', 'trolling'],
      dtype=object)

In [10]:
type(Y)

numpy.ndarray

In [132]:
# def text_cleaning(text):
#     exclude = '!"#$%&\'()*+,-./:;<=>@[\\]^_`{|}~'
#     pattern = re.compile('<.*?>').sub(r' ', text)  # remove html tag
#     pattern = re.compile(
#         r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+').sub(r' ',
#                                                                                                  pattern)  # remove links
#     pattern = pattern.translate(str.maketrans("", "", exclude))  # remove symbols
#     pattern = re.compile("["
#                          u"\U0001F600-\U0001F64F"  # emoticons
#                          u"\U0001F300-\U0001F5FF"  # symbols & pictographs
#                          u"\U0001F680-\U0001F6FF"  # transport & map symbols
#                          u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
#                          u"\U00002500-\U00002BEF"  # chinese char
#                          u"\U00002702-\U000027B0"
#                          u"\U000024C2-\U0001F251"
#                          u"\U0001f926-\U0001f937"
#                          # u"\U00010000-\U0010ffff"
#                          u"\u2640-\u2642"
#                          u"\u2600-\u2B55"
#                          u"\u200d"
#                          u"\u23cf"
#                          u"\u23e9"
#                          u"\u231a"
#                          u"\ufe0f"  # dingbats
#                          u"\u3030"
#                          u"\u23F2"
#                          "]+", flags=re.UNICODE).sub(r'', pattern)
#     pattern = re.sub('[^a-zA-Z]', ' ', pattern)  # remove number
#     pattern = " ".join(pattern.split()).lower()  # convert into lower and multipal
#     return pattern

In [133]:
# tran1 = ColumnTransformer([
#     ('encoding',CountVectorizer(ngram_range=(1,2),max_features=2000),['comment'])
# ])


In [134]:
# pipe = Pipeline([
#     ('tran1',tran1),
#     ('model',model)
# ])

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
vector = TfidfVectorizer(max_features=3000,ngram_range=(1,2))
X = vector.fit_transform(sample2['comment']).toarray()


In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,random_state=12,test_size=0.2)

In [14]:
x_train.shape,y_train.shape

((16563, 3000), (16563,))

In [15]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [17]:
pred = model.predict(x_test)
print(accuracy_score(pred,y_test))
print(confusion_matrix(pred,y_test))

0.9171697657570635
[[ 778   30    4    4    2]
 [  35 1073   30   40   47]
 [  14   33  907   22   12]
 [  12   20   16  710    4]
 [   2    9    0    7  330]]


In [147]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(),x_train,y_train,cv=5)

array([0.56487628, 0.58272947, 0.56582126, 0.59480676, 0.59842995])

In [18]:
import pickle

In [19]:
pickle.dump(vector, open('vector.pkl','wb'))
pickle.dump(model, open('model.pkl','wb'))

In [22]:
mode1l = pickle.load(open('model.pkl', 'rb'))
vector1 = pickle.load(open('vector.pkl', 'rb'))

In [26]:
predt = mode1l.predict(vector1.transform(['what is your name']))
predt[0]

2

In [ ]:
['appreciation', 'normal', 'question', 'suggestion', 'trolling']